### PR TITLE
bump sqlite_async version to 0.9.0

### PR DESCRIPTION
**Pull request by davidmartos96**
Updates sqlite_async version in the package and in the demos, and it updates the drift demo with an up to date version.
Depends on https://github.com/powersync-ja/sqlite_async.dart/pull/65

### CODE REVIEW

**Comment by mugikhan** [comment]
@davidmartos96 can you run `melos prepare` in the monorepo and ensure there are no errors when fetching these dependencies?

As noted in #160,  the `supabase-todolist-drift` demo will fail to fetch it's dependencies when upgrading to `sqlite_async` v 0.9.0.

**Comment by davidmartos96** [comment]
I did run melos bootstrap.
Errors are expected because https://github.com/powersync-ja/sqlite_async.dart/pull/65 is not published yet.
We can mark as draft if you wish

**Comment by mugikhan** [comment]
Hey @davidmartos96 I am unsure about the upgrade of the sqlite3 package as we haven't released our core extension with support for the upgraded version. Could you please run a `melos prepare` and ensure that you don't have any errors?

**Comment by davidmartos96** [comment]
@mugikhan I believe the problem is because this hasn't been merged yet https://github.com/powersync-ja/sqlite3.dart/pull/10

It adds compatibility with `sqlite3` v2.4.6 on Web WASM which is the minimum version that supports `web` 1.0.0, required by `sqlite_async` 0.9.0

**Review by mugikhan — APPROVED** [review]
We've merged the [sqlite3.dart](https://github.com/powersync-ja/sqlite3.dart/pull/10) PR and I've run `melos prepare` locally and it succeeds with no errors.

**Pull request merged**
